from .Links import Links
from .W3c import W3c
from .Item import Item
from .Description import Description
from .MapaDoSite import MapaDoSite
from .MenuHeaderFooter import MenuHeaderFooter
from .ColunaLateral import ColunaLateral
from .Imagens import Imagens
from .Title import Title
from .ScrollHorizontal import ScrollHorizontal
from .PageSpeed import PageSpeed
from .Mpi import Mpi
from .Texto import Texto